{% set name = "uvloop" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 942cd07035510b149d6160796f4e972137130ae953871b6a98c2cf5d5ab68c2e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py2k or win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - python
    - pip
    - cython ==0.29.10
  run:
    - python

test:
  imports:
    - uvloop

about:
  home: http://github.com/MagicStack/uvloop
  # Multiple licenses! : Apache 2.0, MIT
  license: MIT
  license_file: LICENSE-MIT
  summary: Ultra fast implementation of asyncio event loop on top of libuv.
  description: |
      uvloop is a fast, drop-in replacement of the built-in asyncio event loop.
      uvloop is implemented in Cython and uses libuv under the hood.
  doc_url: http://uvloop.readthedocs.org
  dev_url: https://github.com/MagicStack/uvloop

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
