{% set name = "uvloop" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 123ac9c0c7dd71464f58f1b4ee0bbd81285d96cdda8bc3519281b8973e3a461e
  patches:
    - 0001-Prefer-SO_REUSEPORT-over-uv.SO_REUSEPORT.patch

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv --global-option='build_ext' --global-option='--cython-always' --global-option='--use-system-libuv'"
  skip: True  # [py2k or win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - python
    - cython >=0.28
    - pip
    - libuv
  run:
    - python
    - {{ pin_compatible("libuv", max_pin="x") }}

test:
  imports:
    - uvloop

about:
  home: http://github.com/MagicStack/uvloop
  license: MIT OR Apache-2.0
  license_file: LICENSE-MIT
  summary: Ultra fast implementation of asyncio event loop on top of libuv.
  description: |
      uvloop is a fast, drop-in replacement of the built-in asyncio event loop.
      uvloop is implemented in Cython and uses libuv under the hood.
  doc_url: http://uvloop.readthedocs.org
  dev_url: https://github.com/MagicStack/uvloop

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
